### ISSUE TITLE
vite 5 support

### ISSUE THREAD

**Issue by harry-73** [JorgenVatle/meteor-vite#126]
Hi,

Is there plan to support vite 5?

Thanks.

**Comment by JorgenVatle** [comment]
There is! I don't believe the plugin is incompatible with Vite v5. We're just waiting on Meteor v3, as Vite v5 dropped support for Node.js 14 - which is the version Meteor v2 uses internally. 

If there is a need for Vite v5 for users on Meteor v2, there are certainly ways to get around this, as I assume most people will have a newer version of Node.js already installed that we can use instead when firing up Vite from Meteor. But I've opted not to put much time into that as I don't think the complexity of managing two Node.js installs for your environment makes the upgrade worthwhile.  

But again, I'm open to add support if there is a real need. I'd love to hear some use cases. 🙌

**Comment by harry-73** [comment]
In fact, I use the package `vite-plugin-vuetify` and it has as peer dependencies `vite  >=5`:

```
"peerDependencies": {
        "vite": ">=5",
        "vue": "^3.0.0",
        "vuetify": "^3.0.0"
      }
```
So I have some error running npm.

But at least everything to work.

**Comment by JorgenVatle** [comment]
Yeah, most plugins have recently upped their major version to match the new Vite release. Usually there aren't any major changes apart from the Vite v5 version bump.

https://github.com/vuetifyjs/vuetify-loader/blob/master/packages/vite-plugin/CHANGELOG.md#-breaking-changes

The following snippet should fix those warnings for you. I'll be sure to add Vite v4 as a peer dependency for our plugin so npm won't try to install incompatible plugin versions.
```sh
meteor npm i vite-plugin-vuetify@1
```

**Comment by harry-73** [comment]
Thanks.
