### ISSUE TITLE
[QUESTION] Version difference on atmospherejs website

### ISSUE THREAD

**Issue by dispbd** [JorgenVatle/meteor-vite#17]
In CHANGELOG, the latest version of vite-bundler is listed as 1.1.3, but on the [atmospherejs](https://atmospherejs.com/jorgenvatle/vite-bundler) the version is lower.
![](https://i.vgy.me/3EhiDT.png)

I understand correctly that changes are published with a delay in the atmosphere? Is that how it should be? Or are there manual publications at all?

**Comment by dispbd** [comment]
Whenever possible, turn on the labels. :sweat_smile:

**Comment by JorgenVatle** [comment]
You mean issue labels? Can't seem to find any settings for it 🙈

The version available on GitHub can be one version ahead of what's available on npm/Atmosphere. I'm using `changesets` to manage versions for the packages. So the latest version could be published or still in development. If it is a pending release, there should be a "Version Packages" pull request active in the repository. Once it's merged, the changes are published to npm/Atmosphere.

Just went ahead and published the last update in case there were some important fixes there. 😄

**Comment by dispbd** [comment]
You can probably enable them in the labels section.
![](https://i.vgy.me/0dZvmf.png)

The problem with this is that in npm the version is available as soon as you release it, but in atmospherejs the version is old (and still 1.1.1). Naturally, because of this mismatch, launch errors appear. To avoid this, you always have to manually copy the vite-bundler folder, which is not very convenient.
Is it possible to make a new version appear as quickly in atmospherejs as in npm?
Or is it not up to you? I'm sorry, I just didn't understand very well :sweat_smile:

**Comment by JorgenVatle** [comment]
Oh, I'm so sorry. Looks like the workflow for publishing packages to Atmosphere was silently failing due to some missing types. Just shipped a fix and the latest version should be up in a few moments. 🙏

**Comment by dispbd** [comment]
Thanks for your work!
