### ISSUE TITLE
Assets.getText is not a function

### ISSUE THREAD

**Issue by timsun28** [JorgenVatle/meteor-vite#184]
Got this error while in dev mode that originated from this line:
https://github.com/JorgenVatle/meteor-vite/blob/d82fc0838302bfc407c9eb68129c23dc65cefe2d/packages/vite-bundler/src/loading/vite-connection-handler.ts#L30

This function is now renamed to getTextAsync as can be read [here](https://v3-migration-docs.meteor.com/api/renamed-functions.html#assets-gettext).

I would be happy to add this small change to a pr (tested locally, just needed to change the stringTemplate() function to async and changed the function name). 
To what branch would this best be done? 

[Update]
It appears a pr is already made, this issue can be closed when the pr is merged

**Comment by bomb-on** [comment]
There is already a PR for this issue: https://github.com/JorgenVatle/meteor-vite/pull/180
