### ISSUE TITLE
Entry points not using Vite.resolve.alias definitions.

### ISSUE THREAD

**Issue by digitalextremist** [JorgenVatle/meteor-vite#198]
Using these path alias definitions in `vite.config.js` at `resolve.alias {}`

![image](https://github.com/user-attachments/assets/1b3e4333-2a0a-445b-a4f6-00a441543dfc)

And using these `paths` in `tsconfig.js`

![image](https://github.com/user-attachments/assets/e9dd04eb-5750-4063-bc36-ff27c7f2f6c3)

And then these `mainModule` entries in `package.json`

![image](https://github.com/user-attachments/assets/02911bb4-680a-4346-9e0b-17288d04839b)

When using `meteor` with or without `--settings <file path>`

I then get `Unable to resolve some modules:` for every `import` using a path alias, such as `@imports/path/file`

And this will be true for `web.browser` and `web.browser.legacy` for the client application, which will be the same errors; then also `os.linux.x86_64` for the server application.

`meteor` will then suggest using `meteor npm install --save` on each entry, as if it were not an alias but a potential package.

Then `Starting Vite server...` will arise, and it wil crash with `Error: Cannot find module` at the first use of an alias.

---

This seemed to work previously, but something looks like it changed.

Are we not allowed to use alias paths, or am I doing something wrong, or was there a breaking change?

**Comment by JorgenVatle** [comment]
Make sure those import aliases aren't being used from your `client/***.ts` or `server/***.ts` mainModules. I suspect you might have some server code that is importing a file containing those aliases.

Meteor doesn't adhere to path aliases defined in your `tsconfig.json` file unless I'm mistaken. Assuming this is the issue, you can work around it by adding either also defining them in a `.babelrc` file which is respected by Meteor. Or using a different typescript compiler for the Meteor server. E.g. [`refapp:meteor-typescript`](https://packosphere.com/refapp/meteor-typescript) or [`jorgenvatle:tsup`](https://github.com/JorgenVatle/meteor-tsup)

For the `.babelrc` route, the following plugin should do the trick for you.
https://www.npmjs.com/package/babel-plugin-module-resolver

Also, which versions of `meteor-vite` and `jorgenvatle:vite-bundler` are you using?

**Comment by digitalextremist** [comment]
Ninja @JorgenVatle; thank you! That resolved the issue: `.babelrc` with `module-resolver` as follows:

![image](https://github.com/user-attachments/assets/e8209959-1610-4bc9-be39-8354b9d246b4)

**Comment by digitalextremist** [comment]
Mentioned this issue here: https://forums.meteor.com/t/special-purpose-entry-points-beyond-client-server/62479/4

Seems like this will be the launch-point for me to get into the package with you @JorgenVatle and build toward multiple entry points beyond `client` and `server` but being headless `agents` at first-class at the macro-design level.

In retrospect I am glad to have had trouble getting into `3.0.4` and I appreciate this repository very much.
