### ISSUE TITLE
bundle/ being injected into server/

### ISSUE THREAD

**Issue by digitalextremist** [JorgenVatle/meteor-vite#215]
Pardon the premature/incomplete initial version of this issue. And also this issue has dramatically shifted around while tracing through it, so the subject only reflects the lasting issue, but I left the blow-by-blow of how I got there.

---

Trying to track this down, and not sure if it is this package or `meteor` itself... but after updating to `3.0.4` several strange things seemed to happen, top two being:

- Infinite loop as mentioned in subject, but more so
- `bundle/` being added to `server/` directory ( rather than `meteor/` presumably ) with this added to the top of the server entrypoint:

```
import("./bundle/meteor.server").catch((e) => console.warn('Failed to load Vite server bundle. If this is the first time starting the server, you can safely ignore this error.', e))
```

As I go down this sudden and unexpected rabbit hole at an update, I am all ears for what might have caused this! Otherwise will report back with the solution once I find it. Might need to roll-back to an older version and see if I can reproduce it.

**Comment by digitalextremist** [comment]
So far, upon rolling back I am now getting:

```
Error: [MeteorViteWorker] Missing required METEOR_RUNTIME environment variable
```
Seems like something fundamental broke somewhere. I deleted `node_modules/` and `package-lock.json` and reinstalled with `meteor npm install` using a rolled-back point that worked previously, so this is disconcerting.

Will step away for a bit and return fresh, and possibly with a clue on what might have happened?

**Comment by digitalextremist** [comment]
( And now seeing infinite loop of: )

```
W20241020-20:55:12.268(-7)? (STDERR) Node.js v20.17.0
I20241020-20:55:26.551(-7)? ⚡   Refreshing configuration from Vite dev server...
W20241020-20:55:26.553(-7)? (STDERR) Oops worker process is not connected! Tried to send message to worker: { method: 'vite.server.getConfig', params: [] }
I20241020-20:55:26.553(-7)? The Vite server is likely running in the background. Try restarting Meteor. 👍
I20241020-20:55:26.555(-7)? ⚡   Refreshing configuration from Vite dev server...
```

This is allegedly using `jorgenvatle:vite-bundler@2.0.1` but am seeing `meteor-vite` at version `1.11.1` as well, which I thought coincided with `2.1.3` of `vite-bundler`? Very strange behaviors and not yet running out ghosts and aliens.

**Comment by digitalextremist** [comment]
Update here... pardon the spam. Alright so, I seem to have cleaned up _something_ and am now left with only the `server/bundle/` issue for some reason. Updating the title to reflect that.

Upon roll-back this time I tried to step `vite-bundler` forward to `2.1.3` and that got it back to running again, once ignoring this error in the browser:
![image](https://github.com/user-attachments/assets/261b17bd-fd71-4aca-b7f4-627cf7b128f9)

And the error in the CLI from the above `server/bundle` injection:

```
(STDERR) Could not resolve "./bundle/meteor.server" from "server/MY_ENTRYPOINT.ts
```

**Comment by digitalextremist** [comment]
And when removing the injections, this shows until restart of the server:

![image](https://github.com/user-attachments/assets/d7a3438a-67dc-4fee-badd-17928a12b31f)

**Comment by JorgenVatle** [comment]
We shipped some changes last week that reworked how the Vite and Meteor dev servers communicate. I suspect those changes are related to the issues you're seeing. 

Most likely there's a version mismatch between `jorgenvatle:vite-bundler` and `meteor-vite`. Admittedly, I was a bit quick to push out some releases for these during the upgrade, so some releases may be broken. 

If you're using `jorgenvatle:vite-bundler@2.1.3`, make sure you also grab the latest release of `meteor-vite`. 
```sh
meteor npm i meteor-vite@latest
```

Meteor will sometimes try to install older releases despite what's set in your `.meteor/packages` file. So it can be worthwhile to run `meteor add jorgenvatle:vite-bundler@2.1.3` and then verify by checking your `.meteor/versions` file.

If all else fails, you can just roll back to `jorgenvatle:vite-bundler@2.0.3` and `meteor-vite@1.11.1` which should be stable.

**Comment by JorgenVatle** [comment]
Oh, disregard all of the above. What does your `vite.config.ts` file look like?

  ```ts
  // vite.config.ts
  export default defineConfig({
    plugins: [
      meteor({
        clientEntry: "./client/main.vite.ts",
        serverEntry: "./server/main.vite.ts", // Write your server code from this entrypoint.
      }),
    ],
  });
  ```

If your plugin config looks like this, just comment out the `serverEntry` field. It's an experimental feature for pre-bundling your Meteor server with Vite. It needs some additional configuration to work correctly.

**Comment by digitalextremist** [comment]
I use a custom name for both entry points, so it looks like this ( I just added `./` to fit your example, now ):

![image](https://github.com/user-attachments/assets/bc0efa89-a13a-4226-b068-8251c8653594)

When `server/bundle/` is created, there are only images in it; icons and other assets.

The disturbing thing is that the code would get an injection at all, since this type of thing ought to be built into `./dist` or `./lib` usually, and it diminishes trust to have artifacts added without knowledge/consent, and then that removes a feeling of sanity.

I did also do all the `vite-bundler` and `meteor-vite` attempts you mentioned there, before seeing to disregard that ( going off the original email notifications before edits ) and there was no effect. Am using latest versions of both.

**Comment by digitalextremist** [comment]
To reiterate, the two issues on this are the injection of `server/bundle/` and the line of code at start of `serverEntry` file, then also this popping on the client:

![image](https://github.com/user-attachments/assets/257b0622-2e3d-4774-85cc-62b63ee20d61)

Right now this prevents pushing to `production`, but can be clicked through or ignored in the `development` environment.

**Comment by JorgenVatle** [comment]
Just remove the serverEntry field from your plugin config and you should be fine. Make sure you also remove the async import written to your Meteor server entry and the `dist/` directory located next to the server entry 👍

The feature was introduced last update and hasn't received documentation yet. I'll make sure to remove the type definition for it until it's fully documented to avoid further confusion. 😅

Meteor-Vite operates by replacing the entry points you would normally specify in your `package.json` with the entry points specified in your Vite config. Ideally the content of your Meteor entrypoint files (the ones specified in `package.json`) should be empty and added to `.gitignore` to prevent accidentally committing any changes added by Meteor-Vite. 

When bundling Meteor-Vite will write imports for Vite's build output to the entrypoints specified in `package.json`. Again, not to be confused with the entrypoints configured in `vite.config.ts`. As clunky as it is, it's the most reliable way to intercept Meteor's build process.

**Comment by JorgenVatle** [comment]
The files added to the `dist/` directory is just the default build output from Vite. Similar to what you would get when running `vite build`. You're safe to delete it. It will only be created during development when using the `serverEntry` setting.

**Comment by JorgenVatle** [comment]
> The disturbing thing is that the code would get an injection at all, since this type of thing ought to be built into ./dist or ./lib usually, and it diminishes trust to have artifacts added without knowledge/consent, and then that removes a feeling of sanity.

Absolutely agree with you on this. At least for the client, we do our best to warn you about this when you have existing content in your client entry. The `serverEntry` was a recent addition and isn't really something I expected anyone to notice before documentation was in place. 😅

The only files that are written to are the two entry modules specified in your `package.json`. Your Vite config is essentially superseding those entrypoints that would normally be used by Meteor.

**Comment by digitalextremist** [comment]
Thanks for the deep comments to help me understand `meteor-vite` ( and `vite-bundler` it would seem? Not totally sure if the difference and your vision for smoothing out `Vite` support, since it seems you took over dormant/pre-existing `Vite` support )

I seem to trust you. I appreciate your sharing my position on the sanctity of source, and not wanting to watch for tools to change developer space, versus just use transient/build/test space, similar to `/tmp` versus `/home` sovereignty, in how we see files.

All this being said, that did not seem to work. In `./vite.config.ts` when there is no `plugins[meteor(serverEntry)]` then `Vite` will not build at all, but I wonder now if my `package.json` is wrong, given its importance/primacy given what you said, and the fact that the error message dumps the contents of `package.json` and complains of there being no `server` entrypoint:

> FatalMeteorViteError: You need to specify an entrypoint for Vite!

Here is that segment of `package.json`

![image](https://github.com/user-attachments/assets/6ae3253a-583e-4391-9ee3-a94ba1194d76)

I have not reverted back to use the standard file names, but it does seem like my use case is being pressured by that aspect? Not sure of how much is hard coded, such as `client` and `server` themselves, as key terms. I would rename those if I could.

---

Upon reading your comments again, I will need to reassess this and I might be expecting different behavior than is correct. Will do that in the interim, and perhaps start to get to know this repository more in-depth since I seem to be relying on it, and you, when I might be add something in return. Thanks again for your vigilance and insight. I very much appreciate your work.

**Comment by JorgenVatle** [comment]
Just did a little overhaul to the readme to avoid any confusion around these entry modules. I've caught myself confusing them quite a few times.

You will need 3 entry modules for your app. Here's an example app structure where Vite is only responsible for bundling client code:

```text
- client/
  - entry-vite.ts        # Write your client code from here.
  - entry-meteor.js      # Leave empty, Vite will write to this file to load missing dependencies at runtime.
  - index.html
- server/
  - main.ts
bundle.
- package.json
- vite.config.ts
```

```json5
// package.json
{
  "meteor": {
    "mainModule": {
      "client": "client/entry-meteor.js",
      "server": "server/main.ts"
    }
  }
}
```

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    meteor({
      clientEntry: 'client/entry-vite.ts'
    })
  ]
})
```

---
The server builds feature should also be fixed now, so if update to `jorgenvatle:vite-bundler@2.2.0` and `meteor-vite@1.12.0` your original configuration should work.

**Comment by digitalextremist** [comment]
Thanks for the clear `README.md` snippet, and that makes more sense... and now it works again!

After updating to `2.2.0` and `1.12.0` of those two packages, then removing the artifacts added to the server application by the past issue, and thoroughly understanding what is going on now, thank you very much, it seems clearer and functions as expected!

---

If you have a moment to point me to the answer of what the difference between or relationship between `vite-bundler` and `meteror-vite` are, or why they share this repository if not, that would be great. 

You seem to pick up and carry relevant things, and I am curious to know how you see the future of this package. And I wonder, does anything other than `meteor` use `vite-bundler` from here?

**Comment by JorgenVatle** [comment]
The two packages serve different responsibilities.

`jorgenvatle:vite-bundler` is a Meteor build plugin. Only packages published through the Meteor package repository (Atmosphere) can interact with Meteor's build system. Though despite it's classification, it doesn't do any building. All it does is launch the `meteor-vite` npm package as a separate Node.js process which then takes care of building and HMR functionality provided by Vite.

Because of limitations with Meteor's build system, the easiest and most backwards compatible approach was to just publish two separate packages, delegating primary functionality onto the npm package.

**Comment by JorgenVatle** [comment]
The primary benefit is that we can publish multiple versions of `jorgenvatle:vite-bundler` that conform to Meteor's version requirements. E.g. for Meteor v3 and v2, where the npm package does not need to be updated with every breaking change to Meteor's core dependencies.

**Comment by digitalextremist** [comment]
Thank you very much for the clarifications @JorgenVatle!

Spreading between `atmosphere` versus `npm` seems like extra work and I am not sure I see the value so far. Seems like that might be a weakness promoted as a strength. I find myself wishing for one and only one package manager as I enter the `meteor` ecosystem. That difficulty makes sense now, for why two packages.

Very grateful for your insight and help understanding the space. Implementing `Vue` and `Tailwind` with `Vite` on `Meteor` does not seem like the first priority for the ecosystem so I am grateful you seem to really care!
