### ISSUE TITLE
[BUG] The build does not compile in production

### ISSUE THREAD

**Issue by dispbd** [JorgenVatle/meteor-vite#23]
In the latest versions, the build in production does not compile. There are no errors in this. The build command seems to be skipped.
Now we have the following command in package.json:
![](https://i.vgy.me/XaLyfe.png)

Has the build command changed? Or is it a bug?

**Comment by JorgenVatle** [comment]
Hey there! 👋

Not sure if I understand - the build script does nothing when executed? 👀 Do you have an example of terminal output I could take a look at when you try running the command?

**Comment by dispbd** [comment]
Hi!

We have production through docker. Not sure what this means for you:
![](https://i.vgy.me/F1FQ5B.png)
Previously, between the lines `jorgenvatle:vite-bundler: updating npm dependencies -- picocolors...` and `DONE 83.6s` there was a build process from Vite.
If I'm not mistaken, before version 1.3 it worked.

I didn’t figure out how to build a production Vite without a docker. If you tell me how, I will provide you with more necessary logs.

**Comment by JorgenVatle** [comment]
Sorry about that! 😱

Looks like the builds were skipped entirely due to a bad environment check. Just shipped a hotfix to resolve it for you 🙏

**Comment by dispbd** [comment]
Everything is working.
Thank you for efficiency!
