### ISSUE TITLE
Imports returning "undefined" for named exports?

### ISSUE THREAD

**Issue by digitalextremist** [JorgenVatle/meteor-vite#230]
As with other issues I am starting here by posting the problem, then trying to figure out it if it is this package or `Meteor`

Am in the process of shifting to a different design pattern which is `client` / `server` / `agent(s)` as mentioned:

https://forums.meteor.com/t/special-purpose-entry-points-beyond-client-server/62479/11

In the process I am abstracting `settings.json` since the `agent(s)` do not have `Meteor.settings` since they do not need `Meteor` at all. So I am reading `process.env.METEOR_SETTINGS` myself to parse the JSON.

For that to work it has to happen early/first in the load process.

I am seeing very weird behavior with that: Named exports seem to return `undefined` at first, and flow continues, but then the values get set later once everything already crashed without the values.

It feels like a race condition, like the imports are happening out of order or in parallel.

Is that possible, or is there a tome of magic I can study to figure out the quantum mechanics of how loading is happening? And does it differ from `Meteor` itself?

**Comment by digitalextremist** [comment]
This was my bad! But it is also not making any sense as to why.

I had used: `await JSON.parse()` 

Changing to `JSON.parse()` without `await` caused it to all work finally.

I feel like there is some raw black magic in the `Meteor` or `Vite` loading process but I cannot put my finger on it. At least for today, since I posted that after dealing with the issue for hours, within <10 minutes it was solved 🤣 

Thanks rubberduckie!

**Comment by JorgenVatle** [comment]
My recommendation would be to try to only read the settings after a `Meteor.startup()` hook. In development, the `METEOR_SETTINGS` environment variable is defined at runtime, whereas in production it is defined before starting the server. Since Meteor can take a second to boot up, it's very possible you are running into a race condition.

`Meteor.startup()` is a way to work around it. It will fire as soon as Meteor is ready and has applied (almost) all internal configuration. This shouldn't be an issue in production however, at least for `METEOR_SETTINGS`.

**Comment by digitalextremist** [comment]
This is good advice. Since I am abstracting though, part of the problem is that I do not have `Meteor.startup()` loaded either, in the case of `agents` versus `server` or `client` ... so I handled it by having a shared bash-script based "exfoliator" of the JSON. It takes a path set in `docker-compose.yml` and then loads it with `cat` into the environment variable `Meteor` expects, and which I also parse myself outside its influence and control, but with perfect continuity. Well, as much as environment variables offer.

I am on a deep-dive into all the `Meteor` internals, and you might have a message in your spam box where I offer to use this experience ( which will be a few months of getting far into `Vite` and knowing `meteor-vite` inside and out by the end hopefully ) to help get the cart behind the horse since you seem to be "the guy" and yet are off on a fork. At the very least I will keep reporting on what comes up and hopefully keep surfacing gotchas and edge cases to help harden this vital, essential, leading package.
