### ISSUE TITLE
Does meteor-vite ignore package.json#imports by default, or is meteor-tool trimming wings?

### ISSUE THREAD

**Issue by digitalextremist** [JorgenVatle/meteor-vite#231]
Notes here: https://forums.meteor.com/t/how-to-make-meteor-unignore-package-json-imports-inside-dependencies/62493/1

`package.json#imports` seems ignored in at least one case, but in looking at that convention... wow would I love to use that instead of setting aliases in three places.

Thought to ask the solo ninja wizard around here while pursuing this. Please let me know if there is a better place for issues which start out as questions but might turn into items to resolve if there is a problem.

**Comment by digitalextremist** [comment]
Tracing the issue found in `Vite` and mentioning my case specifically: https://github.com/vitejs/vite/issues/7385#issuecomment-1200930137

With official term `subpath imports` https://nodejs.org/api/packages.html#subpath-imports

**Comment by digitalextremist** [comment]
This exact case is also brought up here: https://www.npmjs.com/package/resolve.imports#subpath-imports

**Comment by digitalextremist** [comment]
Seems to be unclear whether this is active, though allegedly merged:

https://github.com/vitejs/vite/pull/7770#issuecomment-2138421382

For the record I am using `Vite` version `4.5.2`

**Comment by digitalextremist** [comment]
So far have tried `@rollup/plugin-node-resolve` and `vite-tsconfig-paths` and changing `tsconfig.json` values to no avail

**Comment by digitalextremist** [comment]
Since the only package involved for right now is `chalk` and there is a lot of fog on this issue, I am bypassing color in logs very sadly and marking to return to this.

**Comment by JorgenVatle** [comment]
Oh, interesting. Never heard of this convention before. If they're saying it's fixed, there shouldn't be anything preventing Meteor-Vite from working with it. If you're on Meteor v3, you can safely update Vite to v5 to give it a try. 👍 

There is one caveat however, the Meteor server does not take your Vite configuration into consideration when compiling. So, unless you're also building the Meteor server with Vite using the `serverEntry` config option, you will have to make sure Meteor also supports the convention, if you intend to use the aliases in code that's accessed by the server.

Otherwise, you can define your import aliases with a `.babelrc` config file, which is processed by Meteor. https://www.npmjs.com/package/babel-plugin-module-resolver

**Comment by digitalextremist** [comment]
Thanks very much @JorgenVatle; I will try `Vite 5` since I am using `Meteor 3` and will check if `chalk` and `package.json#imports` works with that.

And you had advised `babel-plugin-module-resolver` so I have that and will look further into configuration options.

You brought up a burning question of mine: 

Does `Meteor` run its own build process unless using `serverEntry` ( which I believe I am, per my last issue #215 ) such as when building for production? Is there a way for me to be sure `Vite` is also doing the production build?

**Comment by JorgenVatle** [comment]
When using the `serverEntry` option, Vite will just bundle all your server assets into a single file which is then passed onto Meteor for the final build stage. Normally, Meteor will scan your entire project for files to include in the final server and client bundle. But with the `serverEntry` Meteor only has to load a single file which is already built by Vite. 

The process is more or less the same for the client. Unless you're using the [Meteor-Vite v3 pre-release](https://github.com/JorgenVatle/meteor-vite/pull/173) which entirely skips Meteor's build process for client assets. They are all built by Vite and then served as static assets by Meteor in production.

The server will always need to be passed through Meteor's build system though.

**Comment by JorgenVatle** [comment]
When building for production, you should see some messages from Vite logging out the build process. If Vite isn't being used to build for production, you'll likely find that the build fails.

**Comment by digitalextremist** [comment]
Thank you for demystifying that >80% @JorgenVatle, that is much clearer. I seem to be in a good position to leverage the best aspects of `meteor-vite` as well as `Meteor` itself. And on my next build for `meteor-base` I will watch the log very closely.

Will check back once I get this solved and mention the solution. It seems like people specifically mention `chalk` and it might be a roundabout way of drawing attention to this ecosystem if there is `package.json#imports` note in the `README.md` mentioning that "as an example" knowing the vast majority of people get pulled into the issue by that, or `Svelte` I believe.

Making a lot more sense! I value these early difficulties to be able to understand the innards much better. Thanks again!

**Comment by digitalextremist** [comment]
Side question here, and please let me know if this is better off as a separate issue; this is at pre-insanity for me right now:

How hard would it be to add more entry points? Would LOVE to have an infinite number of `agentEntry` and `clientEntry`

Right now I have three+ separate build environments in an omnirepo, but it really should be one codescape with many mire tree-shaken entry points. If I could have `Vite` bundle everything like that... just wow. For now, I dream and anticipate rolling up my sleeves to add support for that without harming the standard/default behavior, so it can become normal even if not widely used.

**Comment by JorgenVatle** [comment]
[`tsup`](https://github.com/egoist/tsup) has pretty good support for multi-entrypoint builds. You can define an array of build configs each with their own entry and output directory.

If you run tsup before you start your Meteor server, you just use a conditional within your app's logic to load the build you need. That way it's all under the same codespace. It'll all still show up in your final bundle, though.

There's also an onSuccess hook - this is fired whenever a build completes. So it could create any number of minimal Meteor apps for you on build completion.

**Comment by digitalextremist** [comment]
What a guy @JorgenVatle, thank you. Will look deeply into that; with any luck, that would achieve the goal of infinite possible `Agent` applications without massive fuss. I appreciate your knowledge inside and outside `Meteor` itself.

Have only 4 `Agent` variants running right now and reconciling between three codebases is going very badly for my sanity. That is a) `Agent` bundling, b) `Shared Library` bundling, and c) `Client` and `Server` built by `Meteor` currently, off on their own.

The new curiosity that pops up right away once you showed a way through this roadblock: How can they be all done with `Vite` and/or be the most optimized? My builds seem to be larger than expected for tiny `Agents` and feels like it is not tree-shaking.

---

Adding direct link to proposed solution: https://tsup.egoist.dev/#multiple-entrypoints

**Comment by digitalextremist** [comment]
Just realized you are so humble you neglected to mention you have your own `tsup` implementation already here:

https://github.com/JorgenVatle/meteor-tsup

Diving in there and going to close this issue since I fell through the question and am regrouping in better conext:

https://forums.meteor.com/t/special-purpose-entry-points-beyond-client-server/62479/15?u=digitalextremist

---

Hit bedrock hopefully: https://github.com/JorgenVatle/meteor-tsup/issues/2
