### ISSUE TITLE
Error with 3.0.0-alpha.3: "Unable to locate Meteor-Vite workers! Make sure you've installed the 'meteor-vite' npm package."

### ISSUE THREAD

**Issue by 9Morello** [JorgenVatle/meteor-vite#248]
Upon running a sample React project, I get the following error:

```
=> Linted your app. No linting errors.  
W20241123-11:33:01.005(-3)? (STDERR) packages/core-runtime.js:189
W20241123-11:33:01.007(-3)? (STDERR)             throw error;
W20241123-11:33:01.007(-3)? (STDERR)             ^
W20241123-11:33:01.007(-3)? (STDERR) 
W20241123-11:33:01.007(-3)? (STDERR) MeteorViteError: 
W20241123-11:33:01.008(-3)? (STDERR) ⚡  Unable to locate Meteor-Vite workers! Make sure you've installed the 'meteor-vite' npm package.
W20241123-11:33:01.008(-3)? (STDERR)  L Install it by running the following command:
W20241123-11:33:01.008(-3)? (STDERR)  L $  npm i -D meteor-vite
W20241123-11:33:01.008(-3)? (STDERR)     at createWorkerFork (packages/jorgenvatle:vite-bundler/src/workers.ts:13:15)
W20241123-11:33:01.008(-3)? (STDERR)     at new ViteDevServerWorker (packages/jorgenvatle:vite-bundler/src/vite-boilerplate/development.ts:19:46)
W20241123-11:33:01.008(-3)? (STDERR)     at module.wrapAsync.self (packages/jorgenvatle:vite-bundler/src/server.ts:10:38)
```

Extra information:
* `meteor-vite` is installed and shows up normally inside `node_modules`.
* I'm using Meteor 3.1, `vite-bundler` 3.0.0-meteor2.next.27, and meteor-vite `3.0.0-alpha.3`.

Any ideas? If there's any extra information I could provide, please let me know.

**Comment by JorgenVatle** [comment]
Ooh, how did you get the `meteor-vite` alpha release? Did it install automatically using the React example? You'll want to install `meteor-vite` v2. The `meteor-vite` 3.0.0-alpha release is still very much experimental and will only work with `jorgenvatle:vite@1.0.0-alpha.0` right now.

Running the following commands should pull down the latest stable-ish releases for Meteor v3.
```sh
meteor add jorgenvatle:vite-bundler@3.0.0-meteor3.next.27
npm i meteor-vite@next
```

**Comment by JorgenVatle** [comment]
If you want to try the [alpha build](https://github.com/JorgenVatle/meteor-vite/pull/235), the following commands should do the trick. Just keep in mind that these releases aren't very stable yet.
```sh
meteor add jorgenvatle:vite@1.0.0-alpha.3
meteor remove jorgenvatle:vite-bundler
npm i meteor-vite@alpha
```

**Comment by JorgenVatle** [comment]
There should be a full release available now for Vite v6

```sh
meteor npm i meteor-vite@3 vite@6
meteor remove jorgenvatle:vite-bundler
meteor add jorgenvatle:vite
```

Please do re-open if you're still running into issues.
