### ISSUE TITLE
Why v-meteor.ts isn't on package?

### ISSUE THREAD

**Issue by gabrieldesousah** [JorgenVatle/meteor-vite#27]
Hi, I understand that I need to recreate the v-meteor.ts in my imports/ui folder, copying from example of this project. It's possible to make available in the package to just code `import {useMethod, autorun, ...} from meteor-vite`?

**Comment by JorgenVatle** [comment]
You should probably just use the [`vue-meteor-tracker`](https://github.com/meteor-vue/vue-meteor-tracker) package instead. I believe the `v-meteor.ts` module is just a leftover prototype for `vue-meteor-tracker`. 😅
