### ISSUE TITLE
Error: @vitejs/plugin-react can't detect preamble.

### ISSUE THREAD

**Issue by henriquealbert** [JorgenVatle/meteor-vite#29]
Error: @vitejs/plugin-react can't detect preamble.
The errors happen as soon as we run the meteor project.

I would love to see it working with React ❤️ 

I created a repo to reproduce the issue: https://github.com/henriquealbert/meteor-vite-react
![Screenshot 2023-09-08 at 09 05 15](https://github.com/JorgenVatle/meteor-vite/assets/59376543/13e8eb0c-12a9-4ded-a4e1-e3625ba60bbb)

**Comment by JorgenVatle** [comment]
Thank you for creating the repo there! 🙌

I'll go through and see what I can do about it in a bit.

Related: #26

**Comment by JorgenVatle** [comment]
Just a quick update on this, using the following snippet instead, explicitly importing from Vite instead of the Meteor web server seems to resolve the issue on my end.

By default the Vite server created by Meteor Vite is available at [http://localhost:5173/](http://localhost:5173/)

```html
<script type="module">
import RefreshRuntime from "http://localhost:5173/@react-refresh" // Local Vite server created by Meteor-Vite.
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>
```

**Comment by JorgenVatle** [comment]
Though, as the above snippet would be shipped into production if you just add it to your Meteor HTML. We can take advantage of some of the internals for Meteor and Meteor-Vite to build a reliable snippet on demand when Meteor is running in development;

```js
// server/main.js
import { WebAppInternals } from 'meteor/webapp';
import { getConfig } from 'meteor/jorgenvatle:vite-bundler/loading/vite-connection-handler';

if (Meteor.isDevelopment) {
  WebAppInternals.registerBoilerplateDataCallback('react-preamble', (request, data) => {
    const { host, port } = getConfig();
    data.dynamicHead = data.dynamicHead || '';
    data.dynamicHead += `
<script type="module">
  import RefreshRuntime from "http://${host}:${port}/@react-refresh"
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
    `
  })
}
```

**Comment by JorgenVatle** [comment]
@henriquealbert I've shipped an example React app that should be working. Do note that the Vite config includes a custom plugin that forces Vite to use the React version bundled by Meteor in case you're using any of the [Meteor React](https://github.com/meteor/react-packages/) packages.

Let me know how it goes. 🙏
[React Example](https://github.com/JorgenVatle/meteor-vite/tree/release/examples/react)

**Comment by henriquealbert** [comment]
It looks good! I'll ask to of our team members to test it. Thank you @JorgenVatle 🙏🏻

**Comment by henriquealbert** [comment]
It worked perfectly! Great work @JorgenVatle 👏🏻
