### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by red-meadow** [JorgenVatle/meteor-vite#36]
Dear @JorgenVatle!

We have been using your package in production for several months and we are very satisfied. We develop a big Svelte app. Performance boost in development is huge: both HMR and server-side changes are processed very quickly. We no longer have performance issues with VS Code as well (native Meteor somehow slows it down on Windows). Thank you!

I opened several issues: #33 , #34 , #35.

I think, you should post about your package on Meteor Forums so more developers can use it (even if React isn't fully supported right now).

Feel free to close this issue, I just wanted to provide some feedback.

**Comment by JorgenVatle** [comment]
Hey there!

I'm glad to hear it! Thank you for the feedback and great & detailed bug reports. 🙌

Been off for a short break, sorry about taking so long to get back to you. I'll try to get through your issues there in the coming week or two. 🙏

**Comment by JorgenVatle** [comment]
Just tidying things up. Thanks again for the feedback. 😄
