### ISSUE TITLE
To generate hashes for this number of chunks (currently 64), you need a minimum hash size of 7, received 6. Check the "output.chunkFileNames" option.

### ISSUE THREAD

**Issue by harry-73** [JorgenVatle/meteor-vite#77]
Hi,

By using `--production` option, I had this error:

`To generate hashes for this number of chunks (currently 64), you need a minimum hash size of 7, received 6. Check the "output.chunkFileNames" option.`

I tried to add inside the `vite.config.ts` the following:
`build: {
    rollupOptions: {
      output: {
        chunkFileNames: `[name]-[hash:7].js`,
        format: 'esm'
      }
    }
  },`

without success.

I have modified into the `npm-packages/meteor-vite/src/meteor/IPC/methods/build.ts` file (line 118), `chunkFileNames: '[name]-[hash:6].js',` by `chunkFileNames: '[name]-[hash:7].js',` and it works.

**Comment by JorgenVatle** [comment]
Oops sorry for that! Shipped a bad patch release a few days ago. A fix is underway. 🙏
